version: "3.9"
services:
    ros:
        build:
            context: ../
            dockerfile: ./docker/ros/Dockerfile
        environment:
            - WHATEVER=whatever
        # devices:
            # - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            - ../ros/catkin_ws:/root/catkin_ws
        command: sleep infinity
    px4:
        build:
            context: ../
            dockerfile: ./docker/px4/Dockerfile
        ports:
            - 127.0.0.1:14540:14540/udp
            - 127.0.0.1:14541:14541/udp
            - 127.0.0.1:14542:14542/udp
            - 127.0.0.1:14543:14543/udp
            - 127.0.0.1:14544:14544/udp
            - 127.0.0.1:14545:14545/udp
            - 127.0.0.1:14546:14546/udp
            - 127.0.0.1:14547:14547/udp
            - 127.0.0.1:14548:14548/udp
            - 127.0.0.1:14549:14549/udp
            - 127.0.0.1:14550:14550/udp
            - 127.0.0.1:14557:14557/udp
            - 127.0.0.1:4560:4560/udp
        command: sleep infinity

volumes:
    lstm-models-volume:
