version: "3.9"
name: px4-ros-dev
services:
    ros:
        build:
            context: ../
            dockerfile: ./docker/ros/Dockerfile
        environment:
            - WHATEVER=whatever
        # devices:
            # - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            - ../ros/catkin_ws:/root/catkin_ws
        command: sleep infinity
    px4:
        build:
            context: ./docker/px4
            dockerfile: ./Dockerfile
        ports:
            - 127.0.0.1:5900:5900/tcp # VNC
            # - 127.0.0.1:14540:14540/udp
            # - 127.0.0.1:14557:14557/udp
            - 127.0.0.1:18570:18570/udp # local GCS
            - 127.0.0.1:14580:14580/udp # local offboard
            - 127.0.0.1:14280:14280/udp
            - 127.0.0.1:13030:13030/udp
            - 127.0.0.1:4560:4560/tcp # Gazebo
        command: sleep infinity

volumes:
    lstm-models-volume:
